<?php


// $Id$	  
/**
 * @file
* Implements the block for quickly post content.
*/

/**
 * Implementation of hook_menu().
	 *
function quicklypost_menu() {
    $items['postform/select'] = array(
     //   'page callback' => 'postform_overlay',
     'title'=>'Post a New Content',
     'page callback' => 'drupal_get_form',
     'page arguments' => array('postselect_form'),
      'access callback' => TRUE,
      'description' => t('Select type to post a new content.'),
      'type' => MENU_CALLBACK
    );
	    return $items;
}*/



/**
* Implementation of hook_block_info().
*/
function quicklypost_block_info() {
  $blocks = array();
  $blocks['quicklypost']['info'] =  t('Quickly Post Form');
  $blocks['quicklypost']['cache'] = DRUPAL_NO_CACHE;   // maybe CACHE_PER_USER ?
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function quicklypost_block_view($delta) {
//	drupal_add_js(drupal_get_path('module', 'quicklypost') .'/quicklypost.js');
   drupal_add_css(drupal_get_path('module', 'quicklypost') . '/quicklypost.css');
   module_load_include('inc', 'popup', 'includes/popup.api');
	//$value='<div class="post popups">Post a New Content '.drupal_render(drupal_get_form('postselect_form')).'</div>';
	$value='<div class="post popups"><a href="'.url('node/add').'">Post a New Content</a></div> ';
	$block['content']=$value;
	return $block;
	
}


/*function postselect_form($form, &$form_state){
	module_load_include('inc', 'popup', 'includes/popup.api');
	$posttype = array ();
	$posttype['Select']= '--Select type--';
	foreach (node_type_get_types() as $type => $type_obj) {
		if(user_access('create '.$type.' content'))
            $posttype [$type] = $type_obj->name;
  }
	$form['posttype'] = array (
				'#type' => 'select',
			//	'#title' => t('Add New Content:'),
				'#required' => false,
				'#default_value' =>  'Select',
				'#options' => $posttype,
				'#ajax'=>array(
					'callback'=>'postform_overlay',
					'wrapper'=>'postform',
					'method' => 'replace',
				),
	);
	$form['ajax_fieldset'] = array(
    '#prefix' => '<div id="postform">',
    '#suffix' => '</div>',
    '#markup' => '',
  );
	if(!empty($form_state['values']['posttype'])){
		module_load_include('inc', 'node', 'node.pages');
		$posttype=$form_state['values']['posttype'];

		if($posttype=='Select'){
			$content='';
		}else{ 
			$content = node_add($posttype);
		//	node_form($node);
		//	$form=array('form'=>'node_add');
		//	popup($form);
		}
		$form['ajax_fieldset']['#markup']=drupal_render($content);
	}
	return $form;
}


function postform_overlay($form,$form_state){
	return $form['ajax_fieldset'];
}*/

function quicklypost_overlay_child_initialize() {
  // Add our custom JavaScript.
  if( arg(0) == 'node' and arg(1) == 'add' ){
  	drupal_add_js(drupal_get_path('module', 'quicklypost') . '/overlay-child.js');
  }
  
}

